name: POAP Test (Triggered by n8n)

on:
  workflow_dispatch:  # Permite trigger manual/API
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Install Playwright
        run: npx playwright install chromium
      
      - name: Run test
        run: node poap-form-test.js
        
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: poap-test-videos
          path: 'videos/**/*.webm'
          retention-days: 7
